name: build

on: [push]

jobs:
  make-job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
    - name: Checkout
      uses: actions/checkout@v1 # this is an action by github
    - name: Spark test (Scala)
      id: spark_test
      uses: MLStream/mlstream-spark-udfs/actions@actions_v1 # this is a release in github
      with:
        run-command: "cd spark && sbt test"
    - name: Pyspark test (Python)
      id: pyspark_test
      uses: MLStream/mlstream-spark-udfs/actions@actions_v1 # this is a release in github
      with:
        run-command: "cd pyspark && make integ_test"

